baseURL: "https://paperitivo.netlify.app/"
title: Paperitivo
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10

  l2:
    languageName: "Italian"
    weight: 2
    title: Paperinik in Italiano
    profileMode:
      enabled: true
      title: PaperMod
      # imageUrl: "#"
      # imageTitle: my image
      # imageWidth: 120
      # imageHeight: 120
      subtitle: "☄️ Veloce | ☁️ Fluente | 🌙 Fruibile | 📱 Responsive"
      buttons:
        - name: Blog
          url: posts
        - name: Tags
          url: tags


params:
  env: production
  description: "An informal meeting of young statisticians from the Department of Statistics at the University of Padova"
  author: ["Andrea Mascaretti"] # multiple authors
  ShowReadingTime: false
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Paperinik"
    Content: >
      Welcome to a collection of Paperinik "proceedings".

      - **Paperinik** is an informal meeting of young statisticians from the Department of Statistics at the University of Padova.

  socialIcons:
    - name: twitter
      url: "#"
    - name: github
      url: "https://mascaretti.github.io/"
 

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
